### ISSUE TITLE
missing Wire.onInterrupt(disable_watchdog) routine, compilation terminated

### ISSUE THREAD

**Issue by deHarro** [jbaumann/attiny_daemon#8]
Hi Joachim,

thanks for the elaborated design and DIY explanations for the RasPi UPS HAT!

Sadly I cannot get the firmware for the AtTiny to compile since there is missing code as stated above (Wire.onInterrupt(disable_watchdog)).
How to fix or circumvent this?
Thanks!

Harald

**Comment by deHarro** [comment]
Hi Joachim,

I headed over to puuuu and added your [proposed code fragments](https://github.com/puuu/USIWire/issues/13) into my local copy of his USIWire implementation.

For now this resolves my issue, but how is your preferred solution to that?
Thanks!

Harald

**Comment by jbaumann** [comment]
Hi Harald,

I have a fork in my repository that adds exactly this needed functionality. See https://github.com/jbaumann/USIWire.

Until my proposal for an extension is accepted the simplest way is to download this repository and unzip it in the library folder.

Cheers, Joachim

**Comment by deHarro** [comment]
Hi Joachim,
ok, the usual missing "über den Tellerrand schauen" :)
I concentrated on the UPS stuff and missed the lib, sorry.

I try to implement your daemon with a Digispark module, but I run into issues when compiling for the Digispark:

- error: 'State' is not a class or namespace
- error: 'Register' is not a class or namespace
- error: 'Reset_Configuration::Value' is not a class or namespace

If I choose AtTiny85 as device, all is well.

Any advice on that?
Thanks!

Harald

**Comment by jbaumann** [comment]
### Explanation
That one is simple. Every board definition can contain a definition of all the tools that are needed to compile the software for the specific board and hardware. If this is used then it nails down e.g. the version of the compiler used.
Digistump has done this and since the package definition is quite old the compiler used in that definition is quite old as well. The code that I've written uses newer compiler functionality and does not work with very old compiler versions.
### Fix
Depending on the system on which you run the IDE and on your knowledge of the underlying system different ways are possible to solve this. I would suggest one of the following:
1. If your system allows symbolic links and you know that you don't need the old compiler anymore you can substitute the old compiler directory with a link to the newest compiler version.
These directories can be found in `<Arduino Directory>/packages/arduino/tools/avr-gcc`. You can determine the Arduino Directory by looking for the location of the preferences.txt file in the Preference Pane.
2. Edit the package definition. This is named `package_digistump_index.json` and can be found in the Arduino Directory as well.
In the file look for the definition of the "Tool Dependencies" in "Digistump AVR Boards" or simply search for the string "4.8.1-arduino5". Change this to the name of the directory for your newest compiler, in my case "7.3.0-atmel3.6.1-arduino7".

These modifications should be done when the Arduino IDE is not running.

When you restart the Arduino IDE it should use the newest compiler and the next problem will be that the EEPROM-library cannot be found. Simply copy the library from the ATTinyCore definition to the Digistump definition and you should be good to go. The respective directories on my system are
`<Arduino Directory>/packages/ATTinyCore/hardware/avr/1.3.3/libraries`
 and `<Arduino Directory>/packages/digistump/hardware/avr/1.6.7/libraries`.

**Comment by deHarro** [comment]
Wow, thanks a lot!
This did the trick.

I normally use Visual Studio with the VisualMicro extension to code for my Arduinos and such, but sometimes I fall back to the IDE.
Will this change be transparent for all other projects I have with Digisparks, or have I to revert to the original setting, when I work on other projects?

Can you please explain, why the deamon code is nailed to 8 MHz? (The Digispark has to run at 16,5 MHz to get the USB connection done (only at program time)).

Thanks!

Harald

**Comment by jbaumann** [comment]
My brilliant idea in using the ArduinoIDE was to use something that poses a minimal problem even for beginners. I normally use IDEs that offer a minimum of user support (e.g., Visual Code, Eclipse, Intellij Idea...).

The change I suggested is a general change for all projects with Digisparks. If you are familiar with JSON structures, then simply copy the whole list entry (i.e., the object with the name "Digistump AVR Boards"), give it a new name e.g., "Digistump AVR Boards New Compiler" and change the dependency definition there.

This introduces a new menu with the given name and leaves the rest untouched.

Regarding the clock frequency: The datasheet says on p.163 in figure 21-1 and 21-2, and on  p. 172 in figure 22-2 that 2.7V and 10 MHz go hand in hand. If we want to guarantee that the processor runs without problems even at 3V or below, we cannot go above 8MHz. With 16MHz we would need a stable 4V, and this is simply not sensible with a LI-Ion battery that goes below 3V without damage.

**Comment by deHarro** [comment]
That, too, was the idea behind my approach to use a Digispark as controller. If it had beeen feasible to program the controller without a dedicated programming device, that would have made it even easier for others to build your solution.
But the facts you write regarding the clock frequency kills that approach.

I have to confess, I rigged my test board wrong and didn't catch the drawbacks...
I used the 5V output of the HAT to power the Digispark, what runs perfectly well until the HAT is switched off :-)
The next step, switching the HAT back ON after the battery is recharged, wasn't on my mind til now.

Ok, so I have to revert to a standard AtTiny85, or at least remove some superflous parts on the Spark, which prevent it from normal operation, anyways. I.e. the zener diodes on two IOs for the USB stuff interfere with standard IO stuff.

Tonight I had another idea, but before starting to implement it, I better ask...
Why do you use an analog input to get the battery voltage, having I2C and the corresponding chip on the HAT on hands?
Let me guess... if the HAT is switched off, the chip doesn't answer to I2C requests. True?

Thanks!
Harald

**Comment by jbaumann** [comment]
Since the ATTiny's power supply is the battery, I use the internal voltage reference to determine the battery voltage. I'm currently using the external voltage to determine whether the Raspberry has been turned off, in principle (e.g. if you use a Geekworm UPS 1) this is not necessary and you can measure arbitrary inputs with it (in the range of 0-3.3V, or more precisely the current battery voltage). By leaving the the HAT battery gauge alone I am more independent of hardware details, and actually there are already home-made solutions that do not use the Geekworm UPS.

The chip itself should work even when the UPS is turned off (it is directly connected to the battery). But the RPi has two pull-up resistors which no longer pull anything up when the UPS is turned off... Which means the I2C communications will be problematic at best.

**Comment by deHarro** [comment]
Fine, thank you!
I'm currently at the point where I can say, the Digispark is no good replacement for your board+AtTiny :-)
To get the IOs work as expected, I had to cut out the two resistors at the USB connection (PB3, PB4). That was the easy part.
More difficult was the LED at PB1. On the Digispark the LED is tied to GND and the IO has to provide Plus to get it lit. In turn the voltage at the pin is throttled to the forward voltage of the LED, around 1.6 V.
I unsoldered the resitor and the LED, reversed the LED and connected the resistor to Plus... Mhmm. In the meanwhile I would have carved your board from scratch from a piece of FR4 material ;-)

But more evil than that is my experience with Debian :(
You are a friend of the more advanced versions of everything, as I realized in the past few hours/days.
In turn, my system doesn't recognize "typing" and your skripts don't work.
My struggling to upgrade python to V3.5.x are not very successful up til now.

Do you have a short "how to", to upgrade python 2.7 to 3.5 in principle and moreover this in a way, that even after a reboot, this newer version is active still?

[edit]
Yes, I read all advices on upgrading and installing on Debian Jessi, but to no avail. Lastly I waited 3,5 hours by building python 3.5.2 on the system, until my RasPi told me, that there is some ssh stuff missing :(
[/edit]

[edit2]
I managed to get typing extensions installed and functional.
Probelm left: 
If I start one of your skripts (e.g. readFuses.py) via "mc", it works.
If I enter python readFuses.py o nthe console, I get an error message:

```
pi@raspberrypi:/opt/attiny_daemon $ python readFuses.py 
Traceback (most recent call last):
  File "readFuses.py", line 10, in <module>
    from attiny_i2c import ATTiny
  File "/opt/attiny_daemon/attiny_i2c.py", line 10, in <module>
    from collections.abc import Mapping
ImportError: No module named abc

```
[/edit2]

Thanks!
Harald

**Comment by jbaumann** [comment]
The underlying design philosophy (as far as you can speak of it with such a small PCB) is to **never** pull a pin to a logical high i.e., Vcc. If I did that, then with a full battery at 4.2V I could in theory destroy the Raspberry pins or something else that a user has connected to the board. So the pins have only two states, input floating or output to 0V. Thus the pin can be pulled to whatever voltage is needed with a pull-up resistor and we are sure nothing can happen. As a side effect, you can sink more mA by pulling to low.

Regarding the PCB: I know people who have etched it by themselves, and putting it on a stripboard should be very fast as well :-)

Python2 is no longer supported and everyone should switch to Python3, the sooner the better. Debian normally offers both Python2 (as `python`) and Python3 (as `python3`). The scripts are written for Python3 and I think you could install Python3 on older Debian systems using aptitude and searching for "python3". But I would strongly suggest to update the Debian/Raspbian installation. This works quite well (I had one problem during the last 25 years with Debian) by changing the sources and initiating a "sudo apt dist-upgrade". I would update the current version first, and then go from version to version until you are at Buster.

Lastly, the command you use is calling Python2. You should try `python3 readFuses.py`.

Cheers, Joachim

**Comment by deHarro** [comment]
Hi Joachim,
thanks for the in depth explanation. I'm totally with you, I only reported the findings on reverse engineering the Digispark.
Actually two of my Digisparks now follow your design rules on IO pins and work as expected.

But first I had to change the connection to the battery voltage.
Perhaps this is based on my V1.1 UPS HAT, but when I solder the sense wire for battery voltage to the denoted point (at the diode pin at the side near the coil) I get readings of "battery voltage is 5.02 V" or something like that, as long as the system is powered.
So this side of the diode seems to lead to the voltage after the stepup converter.

As far as I understood the mechanism of your AtTiny_daemon, it will look at the _battery_ voltage and check for the designated levels.

If the voltage is derived from the coil-side of the diode (as stated in your manual) this voltage will be around 5 V as long as the stepup converter is able to maintain the stepup process and so until the battery is more or less dead.

I realized that the manual given side of the diode (near th coil) has 0.3 V below the battery voltage as long as the USP HAT is switched off (no stepping up).

Can you verify that please.
Thanks!

Concerning python:
My Debian is Buster and there are both versions of python (2.7 and 3.5), but I had to activate V3.5 first.
I managed this just a hour ago by using "update-alternatives". Now the skripts react as expected.

Another question:
What is the sense of the button, I attached to the AtTiny?
Does it have any impact on the UPS HAT?
Am I able to shut down gracefully (by issuing the wish to shutdown) the Raspi via this button?
Or can I restart the Raspi with this button?
My findings are: No, none of all.

Harald

**Comment by jbaumann** [comment]
Hi Harald,

I will verify the voltage to be sure that everything is correct. But if you look at the schematic that Brousant provided you can see that the “coil” side of the diode that is connected to VBat is the anode, and the photos show the cathode ring on the other side. So without having measured it the maximum voltage at that point should be the battery voltage. How did you measure the voltage?

The button can have different functions. If the RPi has been turned off for longer than the timeout period, then it restarts the RPi. If the RPi (and the daemon) is running, then you can configure the button to either do nothing, shutdown the system or reboot it. This is part of the config file (option `button function`), and the action defined in the default config file is, as you observed, to do nothing.

Cheers, Joachim

**Comment by deHarro** [comment]
Hi Joachim,
you are right as far as Brousants schematic and the physical situation on the board are concerned.
The ring on a normal diode denotes the cathode, the side where Plus comes out when the diode is in conduction direction.

On the photo you see, that the anodes of the diodes are connected with the plus side of the adjacent battery connector:
![2020-08-22_IMG_2994](https://user-images.githubusercontent.com/26298406/90962944-2b4e0100-e4b4-11ea-9c9d-6c04683da58c.jpg)

Ok, then if you want to connect your sensing wire to the battery, you have to solder it to the anode side, the one witout ring/marking.

You agree?


The button:
If I want to shutdown the Raspi gracefully and restart it by pressing the button, what have I to set in the config file?
And to accomplish the wanted reaction when I have entered the correct setting in the config, have I to press short or  long?

Thanks!

Harald

**Comment by deHarro** [comment]
Hi Joachim,

after having a closer look at your photo and my hardware, I realized, that the layout of Geekworm UPS HAT V1.0 and V1.1 are different.

Your description is correct for V1.0.
V1.1 has to be soldered different.

Harald

**Comment by jbaumann** [comment]
Your photo is pretty clear, and you can solder the cable on to the anode side, or the battery connector, or splice it into the battery cable as well.

Since I do not know exactly how the v1.1 has been changed in comparison to v1.0 I would be careful with the modifications. But maybe the modifications are no longer necessary. If after removing and reconnecting the power the UPS charges the battery, then the UPS can be used without modifications in the same way as the UPS2.

Regarding the graceful shutdown you simply have to change the following line in the attiny_daemon.cfg:

`button function = nothing`

to

`button function = shutdown`

This leads to a shutdown of the system as soon as you press the button. A short press is enough.

After the RPi has shut down and the timeout has been reached (i.e. after `timeout`seconds) the functionality changes. Now if you press the button the UPS will be turned off and on again, effectively leading to a restart of the RPi.

**Comment by deHarro** [comment]
I can confirm that the Geekworm V1.1 HAT has not to be modfied in any form to cooperate with your AtTiny_Daemon in the described manner.
Solely the connection to the battery has to be soldered to the correct side of the diode (the side away from the marking on the diode or better, the side where the connectors PLUS side is directly adjacent).


I changed the button function to be "shutdown".
After pressing the button, the RasPi gracefully shuts down, pressing the button again (after the timeout period), it restarts. Fine.

After two minutes the RasPi restarts without button interaction. 
Is that intentionally?
What have I to set to suppress this behavior?

My config file ist this:
```
[attinydaemon]
button function = shutdown
reset configuration = 3
primed = 1
external voltage constant = 500
external voltage coefficient = 1818
sleeptime = 20
shutdown voltage = 3200
timeout = 120
reset pulse length = 4000
temperature coefficient = 1000
i2c address = 0x37
battery voltage constant = 0
restart voltage = 3900
warn voltage = 3400
temperature constant = -270
battery voltage coefficient = 1000
force shutdown = 1
switch recovery delay = 1000
loglevel = DEBUG
led off mode = false
```

`reset configuaration = 3` leads me to the suspicion, that this is the reason for this behavior.
I have no connection to the RasPis 5 V, the skript _showStateAndBattery.py_ lists the external voltage as beeing 3.9x V, always around 150 mV higher than the battery voltage.

[edit]
No, changing `reset configuaration = 3` to `reset configuaration = 1` doesn't change anything.
After two minutes the RasPi is powered again.
The UPS HAT is not powered off _during_ this time, but after those two minutes it is turned off and on again (resulting in starting the RasPi).

How can I suppress the restart after two minutes?
[/edit]

[edit2]
I realized your addition for UPS HAT V1.1. Fine!

I there again read, that you recommend to attach the P5V to the analog input of the AtTiny to let the AtTiny check the voltage of the RasPi.
As far as I understood the whole thing, the AtTiny has to monitor the _battery voltage_ to know whether and when it has to shut down the RasPi to prevent the battery from depleting too far.
So the only analog input of the AtTiny should be connected to the battery voltage (the red wire from the HAT).
Have I overlooked the second analog input?
Or have I misunderstood the whole functionality?
Please enlighten me.
[/edit2]

**Comment by deHarro** [comment]
One idea, how it may work:
The monitoring of the battery voltage is not issued by the AtTiny but by the daemon running on the RasPi (it can read the battery gauge chip by means of I²C).
If this is true, I'm back in the game and finally understand, how the monitoring of P5V is meant in your description.

This may explain one observation I had when I waited for depletion of the battery to check the setup.
The observation was:
The HAT powered the RasPi, no Power from the mains.
After some time the secondly blink at the AtTiny changed to blink every other second.
After some more time the AtTiny blinked 5 times, the RasPi shut down.
Some time later (now I suspect after 2 minutes), the RasPi restarted and continued to deplete the battery. 
The AtTiny doesn't blink any more, the voltage of the battery was somewhere below 3.2 V (measured with my DVM directly at the battery inputs).
Neither the RasPi nor the AtTiny seemed to check the voltage further, I had to shut down manually and let the battery reload to a sane voltage.

Please comment.
Thanks!

**Comment by jbaumann** [comment]
I have now added a page for the UPS v1.1. Could I use your picture and could I reference your name, and lastly, could you send me a picture of the connection you made for the switch?

The reset configuration describes how the ATTiny tries to reset the UPS. For the UPS v1.0 this is a short pulse (reset configuration 0), for the UPS 2 (and for the UPS 1 v1.1) this is two pulses of about 4s (first turning the UPS off, then turning it on again, reset configuration 1 or 3). The second bit determines whether the ATTiny_Daemon checks the external voltage before the second pulse (in case the UPS is already on). In your case with no connection to the 5V rail of the RPi you should choose the value 1.

If the ATTiny_Daemon is not contacted in regular intervals it assumes that the RPi has shut down (or is inoperative at least). For this I use the timeout interval (and this is why the button only starts the system again after the timeout interval). If the config option `primed` is set it tries to restart the RPi. And this is what happened in your case. By changing the value of primed to

`primed = 0`

The system will no longer be restarted automatically, but the button functionality will remain the same.

Regarding the voltages: The ATTiny on the board uses the battery as its Vcc. This means that I can easily determine the voltage of the battery by measuring the ATTiny’s Vcc voltage. This voltage is then used to determine whether everything is fine, whether the RPi should shut down or whether the ATTiny should turn off the UPS (if it is below the shutdown voltage and force shutdown is set).

In addition I use a pin of the ATTiny (pin 2) to measure an additional voltage, if this is needed. By connecting this using a voltage divider to the RPi rail we can determine whether the UPS is on or off.

**Comment by jbaumann** [comment]
The description until the RPi is shutdown is as it should be. The ATTiny then turns off everything to conserve as much energy as possible. 
What I assume happens now is that the ATTiny tries to turn off the UPS and since you configured the check for the external voltage (which you say returns something like 3.9V) it thinks it still has to turn off the UPS even though it is already off, thus restarting the RPi. If you could try the same with a value of 1 for `reset configuration` then we could verify that. Otherwise you’d have found a bug...

**Comment by deHarro** [comment]
> By changing the value of primed to
> 
> `primed = 0`
> 
> The system will no longer be restarted automatically, but the button functionality will remain the same.

Are there side effects?
Is the UPS functionality still there when "primed = 0"?

I understood your writings as "without prime = 1 the UPS doesn't work as such".
Reading again your description on priming, I now see, only the watchdog functionality is vanished then. 
So, the voltage checks are running still. Correct?

**Comment by deHarro** [comment]
> UPS v1.1. Could I use your picture and could I reference your name, and lastly, could you send me a picture of the connection you made for the switch?

Sure!
I will switch to mail, since I feel tired of holding the different threads together and apart from each other (in my mind... ;)
